apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80  # Exposed port
      targetPort: 80  # Port on the container
  type: LoadBalancer  # Change to NodePort for local environments
